[package]
name = "cli_clock"
description = "A simple Rust binary crate to run a clock in your terminal"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
